### ISSUE TITLE
How to document an array of strings?

### ISSUE THREAD

**Issue by Jeeppler** [ePages-de/restdocs-api-spec#147]
I already looked at #87 and at [spring-restdocs#505](https://github.com/spring-projects/spring-restdocs/issues/505). I am using `restDocsApiSpec: "0.10.0"`. 

My API `api/admin/users` returns a JSON Array containing only strings: `["user1", "user2", "user3"]`.

What I currently get is:

~~~
api-admin-users1367467944:
  type: array
  items:
    type: object
~~~

the corresponding Java Code:

~~~
responseFields(
  fieldWithPath("[]").description("List of user Ids").optional()
).
~~~

What I want is:

~~~
api-admin-users1367467944:
  type: array
  items:
    type: string
~~~

Is there already a workaround for documenting an array of strings in `ePages-de/restdoc-api-spec`? Would somebody be willing to share an example on how to do it?

**Comment by Al3x3i** [comment]
I am not sure if this can help you, you can try
 ` fieldWithPath("[]").description("List of user Ids").optional().type(STRING) `

**Comment by ozscheyge** [comment]
> I am not sure if this can help you, you can try
> `fieldWithPath("[]").description("List of user Ids").optional().type(STRING)`

That's not correct, since the type of the field is not STRING, but ARRAY.

@Jeeppler thanks for reaching out! Idk how this would be done with idiomatic Spring restdocs, since it only allows to document and render the field type (ARRAY in this case).

restdocs-api-spec has some more logic to infer types for the jsonschema:
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-jsonschema/src/main/kotlin/com/epages/restdocs/apispec/jsonschema/JsonSchemaFromFieldDescriptorsGenerator.kt#L228
https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec-jsonschema/src/main/kotlin/com/epages/restdocs/apispec/jsonschema/JsonSchemaFromFieldDescriptorsGenerator.kt#L206

Those parts would need to be improved.

**Comment by Jeeppler** [comment]
@ozscheyge thanks for your response. Based on the links you provided ePages should be able to recognize the array type. However, I was unable to find any documentation on how to do that. Is there a non idiomatic Spring restdocs way using ePages? Would you be willing to share an example or point me to one?

**Comment by ozscheyge** [comment]
Hey @Jeeppler ,

I was only pointing out, which parts of the codebase are responsible for the current behavior and would need to be improved (inference of the JSON schema from example payloads).

With "idiomatic Spring restdocs" I meant proper usage of Spring restdocs according to their API design and philosophy.
This project (restdocs-api-spec) aims to be import-swap-compatible with Spring restdocs, see https://github.com/ePages-de/restdocs-api-spec#migrate-existing-spring-rest-docs-tests . So we are constrained by Spring restdocs capabilities and -for instance- the issue you linked in your original post.
That's also the reason you won't find detailed docs on how to document your tests and payloads using this project: it should be the same as with Spring restdocs, using the same classes and factory methods.

Unfortunately, I don't see an idiomatic way of documenting an array of enum values using Spring restdocs. We could make the JSON schema inference a bit smarter, but it might still be insufficient to match OpenAPI 3 capabilities of exactly specifying possible enum values as elements in an array.

**Comment by Jeeppler** [comment]
@ozscheyge thank you for the detailed explanation.

**Comment by ozscheyge** [comment]
Should be solved with https://github.com/ePages-de/restdocs-api-spec/pull/186

**Comment by Jeeppler** [comment]
#186 did not solve our problem. Even with: `com.epages:restdocs-api-spec-mockmvc:0.16.0`. String arrays are not recognized.
